[workspace]
pr_draft = false
changelog_config = "cliff.toml"
pr_labels = ["release"]
git_release_name = "v{{ version }}"
commit_message = "chore(release): {{ crate_name }} v{{ version }} [skip ci]"
publish = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "zenwave"

[[package.files_to_update]]
path = "README.md"
search = 'zenwave = "[0-9]+\.[0-9]+(\.[0-9]+)?"'
replace = 'zenwave = "{{ version }}"'
